//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaliPazariWinformsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaliPazari_DBEntities : DbContext
    {
        public SaliPazari_DBEntities()
            : base("name=SaliPazari_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tedarikciler> Tedarikciler { get; set; }
        public virtual DbSet<Yoneticiler> Yoneticiler { get; set; }
        public virtual DbSet<YoneticiYetkiler> YoneticiYetkiler { get; set; }
        public virtual DbSet<Alimlar> Alimlar { get; set; }
        public virtual DbSet<SatisDetaylar> SatisDetaylar { get; set; }
        public virtual DbSet<Satislar> Satislar { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunlerView> UrunlerView { get; set; }
    }
}
