//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaliPazariWinformsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikciler
    {
        public int ID { get; set; }
        public string FirmaIsim { get; set; }
        public string TicariUnvan { get; set; }
        public string Sorumlu { get; set; }
        public Nullable<int> Sehir_ID { get; set; }
        public Nullable<int> Ilce_ID { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string MailAdresi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
    }
}
