//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaliPazariWinformsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunlerView
    {
        public int ID { get; set; }
        public string Kategori_Adı { get; set; }
        public string Marka_Adı { get; set; }
        public string Firma_Adı { get; set; }
        public string Ürün_Barkod { get; set; }
        public string Ürün_Adı { get; set; }
        public Nullable<decimal> Birim_Fiyat { get; set; }
        public string Resim { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> Güvenlik_Stoğu { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silinmis { get; set; }
        public Nullable<bool> Hızlı_Satış { get; set; }
    }
}
